---
debug:
  addr: 0.0.0.0:{{ DebugPort }}
  token:
  pprof: false
  zpages: false

http:
  addr: 0.0.0.0:{{ ServicePort }}

tracing:
  enabled: false
  type: jaeger
  endpoint: localhost:6831
  collector: http://localhost:14268/api/traces
  service: {{ trimPrefix Name `ocis-` }}

...
